# Basic Spring Boot Config for Oracle and hibernate config
spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
#        url: jdbc:oracle:thin:@10.30.49.76:1521/ORADB
#        username: basis
#        password: erpbasis0
        url: jdbc:oracle:thin:@192.168.147.138:1521/xe
        username: system
        password: oracle
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        show-sql: true
    rabbitmq:
        host: 192.168.147.138
        port: 5672
        username: guest
        password: guest
# SFTP Info
sftp:
    username: itmuser
    passwd: itmuser
    logfiles:
        10.30.41.80: /oracle/admin/ZHAP5_DOMAIN/aserver/ZHAP5_DOMAIN/servers/AdminServer/logs/ZHAP5_DOMAI{}.[]
        10.30.41.81: /oracle/admin/ZHAP5_DOMAIN/mserver/ZHAP5_DOMAIN/servers/ZHAP5_Srv00{}/logs/ZHAP5_Srv00{}.[]
        10.30.41.82: /oracle/admin/ZHAP5_DOMAIN/mserver/ZHAP5_DOMAIN/servers/ZHAP5_Srv01{}/logs/ZHAP5_Srv01{}.[]
        10.30.41.79: /oracle/admin/ZHAP5_DOMAIN/mserver/ZHAP5_DOMAIN/servers/ZHAP5_Srv02{}/logs/ZHAP5_Srv02{}.[]
        10.30.41.78: /oracle/admin/ZHAP5_DOMAIN/mserver/ZHAP5_DOMAIN/servers/ZHAP5_Srv03{}/logs/ZHAP5_Srv03{}.[]
        10.30.41.69: /oracle/admin/ZHAP5_DOMAIN/mserver/ZHAP5_DOMAIN/servers/ZHAP5_Srv04{}/logs/ZHAP5_Srv04{}.[]
        10.30.41.68: /oracle/admin/ZHAP5_DOMAIN/mserver/ZHAP5_DOMAIN/servers/ZHAP5_Srv05{}/logs/ZHAP5_Srv05{}.[]
        10.30.41.67: /oracle/admin/ZHAP5_DOMAIN/mserver/ZHAP5_DOMAIN/servers/ZHAP5_Srv06{}/logs/ZHAP5_Srv06{}.[]
        10.30.41.66: /oracle/admin/ZHAP5_DOMAIN/mserver/ZHAP5_DOMAIN/servers/ZHAP5_Srv07{}/logs/ZHAP5_Srv07{}.[]
        10.30.41.101: /oracle/admin/ZHAP5_DOMAIN/mserver/ZHAP5_DOMAIN/servers/ZHAP5_Srv08{}/logs/ZHAP5_Srv08{}.[]

# Ssh Configuration
ssh:
    ip:
        - 10.30.148.121
        - 10.30.150.166
        - 10.30.150.168
        - 10.30.150.169
        - 10.30.150.181
        - 10.30.150.251
        - 10.30.47.16
        - 10.30.47.17
        - 10.30.47.31
        - 10.30.47.32
        - 10.30.49.69
        - 10.30.49.70
        - 11.11.4.54
        - 11.11.4.59
        - 11.11.49.131
        - 11.11.49.132
        - 11.11.49.133
        - 11.11.49.134
        - 11.11.8.34
        - 11.11.8.56
        - 11.11.8.57
        - 11.11.8.58
        - 11.11.8.59
    username: itmuser
    passwd: itmuser
    cmd:
        - df -h
        - ifconfig
        - pwd

jmx:
    connection:
        host:
            - 10.30.41.81#8001
            - 10.30.41.81#8002
            - 10.30.41.82#8001
            - 10.30.41.82#8002
            - 10.30.41.79#8001
            - 10.30.41.79#8002
            - 10.30.41.78#8001
            - 10.30.41.78#8002
            - 10.30.41.69#8001
            - 10.30.41.69#8002
            - 10.30.41.68#8001
            - 10.30.41.68#8002
            - 10.30.41.67#8001
            - 10.30.41.67#8002
            - 10.30.41.66#8001
            - 10.30.41.66#8002
            - 10.30.41.101#8001
            - 10.30.41.101#8002
            - 10.30.41.75#8001
            - 10.30.41.75#8002
            - 10.30.41.76#8001
            - 10.30.41.76#8002
            - 10.30.41.77#8001
            - 10.30.41.77#8002
        aserverUrl:
            10.30.41.80
        aserverPort:
            7001
        username:
            checker
        passwd:
            erpbasis0